// Auto-generated by scripts/sync-posts.mjs — do not edit manually
export const posts: { title: string; href: string }[] = [
  {
    "title": "Why Deleting Data Is Harder Than Writing It",
    "href": "https://medium.com/@rudraditya.thakur21/why-deleting-data-is-harder-than-writing-it-e22b648ccbc6"
  },
  {
    "title": "Why Your Program Uses More Memory Than You Think",
    "href": "https://medium.com/@rudraditya.thakur21/why-your-program-uses-more-memory-than-you-think-2c8a96bd1b11"
  },
  {
    "title": "Why More CPU Cores Sometimes Make Your Program Slower",
    "href": "https://medium.com/@rudraditya.thakur21/why-more-cpu-cores-sometimes-make-your-program-slower-97850716c424"
  },
  {
    "title": "The Two Generals Problem: Why Perfect Reliability Is Impossible",
    "href": "https://medium.com/@rudraditya.thakur21/the-two-generals-problem-why-perfect-reliability-is-impossible-c588fdc6cc90"
  }
]
