// Auto-generated by scripts/sync-posts.mjs — do not edit manually
export const posts: { title: string; href: string }[] = [
  {
    "title": "The Two Generals Problem: Why Perfect Reliability Is Impossible",
    "href": "https://medium.com/@rudraditya.thakur21/the-two-generals-problem-why-perfect-reliability-is-impossible-c588fdc6cc90"
  },
  {
    "title": "Why Google Needed Atomic Clocks to Build a Database",
    "href": "https://medium.com/@rudraditya.thakur21/why-google-needed-atomic-clocks-to-build-a-database-8992f9364e56"
  },
  {
    "title": "Inside the Architecture of ClickHouse",
    "href": "https://medium.com/@rudraditya.thakur21/inside-the-architecture-of-clickhouse-0c15d41d69fe"
  }
]
