import { writeFileSync, readFileSync } from 'fs'

const FEED_URL = 'https://medium.com/feed/@rudraditya.thakur21'
const OUT_FILE  = 'lib/posts.ts'

const res = await fetch(FEED_URL, {
  headers: { 'User-Agent': 'Mozilla/5.0 (compatible; portfolio-sync/1.0)' },
})

if (!res.ok) {
  console.error(`Failed to fetch RSS: ${res.status} ${res.statusText}`)
  process.exit(1)
}

const xml = await res.text()

const items = [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(([, item]) => {
  const title =
    item.match(/<title><!\[CDATA\[([\s\S]*?)\]\]><\/title>/)?.[1]?.trim() ??
    item.match(/<title>([\s\S]*?)<\/title>/)?.[1]?.trim()

  const rawLink =
    item.match(/<link>(https?:\/\/[^<]+)<\/link>/)?.[1]?.trim() ??
    item.match(/<guid[^>]*>(https?:\/\/[^<]+)<\/guid>/)?.[1]?.trim()

  // Strip Medium tracking query params
  const href = rawLink ? new URL(rawLink).origin + new URL(rawLink).pathname : undefined

  const pubDate = item.match(/<pubDate>([\s\S]*?)<\/pubDate>/)?.[1]?.trim()

  return { title, href, pubDate }
}).filter(p => p.title && p.href)

// Newest first
items.sort((a, b) => new Date(b.pubDate ?? 0).getTime() - new Date(a.pubDate ?? 0).getTime())

const posts = items.map(({ title, href }) => ({ title, href }))

const content = `// Auto-generated by scripts/sync-posts.mjs — do not edit manually
export const posts: { title: string; href: string }[] = ${JSON.stringify(posts, null, 2)}
`

writeFileSync(OUT_FILE, content)
console.log(`Wrote ${posts.length} post(s) to ${OUT_FILE}`)
